<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RatchetCompanion.Core/RatchetCompanion.Core.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../../ui/src/data/pvar_overlay.json" LogicalName="RatchetCompanion.Games.DL.Data.pvar_overlay.json" />
  </ItemGroup>

</Project>
